const TOKEN = 'TOKEN';
const CAMERA_CURRENT_ID = 'CAMERA_CURRENT_ID';
const SPEAKER_CURRENT_ID = 'SPEAKER_CURRENT_ID';
const MICROPHONE_CURRENT_ID = 'MICROPHONE_CURRENT_ID';
export { TOKEN, CAMERA_CURRENT_ID, SPEAKER_CURRENT_ID, MICROPHONE_CURRENT_ID };
